const httpStatusCode = {
  HTTP_STATUS_CODE_SUCCESS: 200,
  HTTP_STATUS_CODE_CREATED: 201,
  HTTP_STATUS_CODE_ACCEPTED: 202,
  HTTP_STATUS_CODE_NO_CONTENT: 204,
  HTTP_STATUS_CODE_BAD_REQUEST: 400,
  HTTP_STATUS_CODE_UNAUTHORIZED: 401,
  HTTP_STATUS_CODE_FORBIDDEN: 403,
  HTTP_STATUS_CODE_NOT_FOUND: 404,
  HTTP_STATUS_CODE_METHOD_NOT_ALLOWED: 405,
  HTTP_STATUS_CODE_CONFLICT: 409,
  HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR: 500,
  HTTP_STATUS_CODE_NOT_IMPLEMENTED: 501,
  HTTP_STATUS_CODE_BAD_GATEWAY: 502,
  HTTP_STATUS_CODE_SERVICE_UNAVAILABLE: 503,
  HTTP_STATUS_CODE_GATEWAY_TIMEOUT: 504,
};
module.exports = httpStatusCode;
